site_name: NEAR for Advanced Users
nav:
  - Intro: index.md
  - Concepts:
    - Basic: basics.md
    - Deployment: deployment.md  
    - Execution: execution.md
    - Storage: storage.md  
    - Cross-contract Calls: cross-contract-calls.md
    - Gas: gas.md  
  - Common Issues: issues.md

theme:
  name: material
